#version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  api:
    build: ./backend
    env_file:
      - ./.env
    container_name: mia-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - AWS_ACCESS_KEY_ID=${BUCKET_USER_ID}
      - AWS_SECRET_ACCESS_KEY=${BUCKET_USER_SECRET}

  frontend:
    build: ./frontend
    container_name: mia-frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

